version: 2
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/bakito/semver/version.Version=v{{.Version}}
  goos:
  - linux
  - windows
  goarch:
    - 386
    - amd64
  hooks:
    post: upx {{ .Path }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
